import { signIn, logOut } from "./User";
import {
  clientProfile,
  partnerDetail,
  familyMemberDetail,
  insertClientMember,
  updateClientProfile,
  updateClientProfileEmail,
  clientProfileSaveAddress,
  clientProfileSavePhone,
  clientProfilePassport,
  clientProfileMedical,
  onUpdateClientMember,
  onGetClientEmployer,
  onAddClientEmployer,
  onAddJobHistory,
  onAddQualification,
  onUpdateClientEmployer,
  onGetJobHistory,
  onPutJobHistory,
  onGetQualification,
  onPutQualification,
  onGetAllCountries,
  onGetPartnerJob,
  onGetPartnerQualification,
} from "./ClientProfile";
import { getVisaStatus, getAllVisaStatus } from "./VisaStatus";
import { getEducationHistory } from "./EducationHistory";

export {
  signIn,
  clientProfile,
  logOut,
  partnerDetail,
  familyMemberDetail,
  insertClientMember,
  updateClientProfile,
  updateClientProfileEmail,
  clientProfileSaveAddress,
  clientProfileSavePhone,
  clientProfilePassport,
  clientProfileMedical,
  onUpdateClientMember,
  onGetClientEmployer,
  onAddClientEmployer,
  onAddJobHistory,
  onAddQualification,
  onUpdateClientEmployer,
  getVisaStatus,
  getAllVisaStatus,
  onGetJobHistory,
  onPutJobHistory,
  getEducationHistory,
  onGetQualification,
  onPutQualification,
  onGetAllCountries,
  onGetPartnerJob,
  onGetPartnerQualification,
};
