// LOGIN

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const CLIENT_PROFILE_SUCCESS = "CLIENT_PROFILE_SUCCESS";
export const CLIENT_PROFILE_FAILURE = "CLIENT_PROFILE_FAILURE";

export const GET_PARTNER_DETAIL_SUCCESS = "GET_PARTNER_DETAIL_SUCCESS";
export const GET_PARTNER_DETAIL_FAILURE = "GET_PARTNER_DETAIL_FAILURE";

export const GET_FAMILY_MEMBER_SUCCESS = "GET_FAMILY_MEMBER_SUCCESS";
export const GET_FAMILY_MEMBER_FAILURE = "GET_FAMILY_MEMBER_FAILURE";

//GET CLIENT MEMBER
export const POST_CLIENT_MEMBER_SUCCESS = "POST_CLIENT_MEMBER_SUCCESS";
export const POST_CLIENT_MEMBER_FAILURE = "POST_CLIENT_MEMBER_FAILURE";

//LOGOUT
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

//PUT API CLEINT PROFILE
export const PUT_CLIENT_PROFILE_SUCCESS = "PUT_CLIENT_PROFILE_SUCCESS";
export const PUT_CLIENT_PROFILE_FAILURE = "PUT_CLIENT_PROFILE_FAILURE";

//POST API EMAIL
export const POST_CLIENT_EMAIL_SUCCESS = "POST_CLIENT_EMAIL_SUCCESS";
export const POST_CLIENT_EMAIL_FAILURE = "POST_CLIENT_EMAIL_FAILURE";

//POST API ADDRESS
export const POST_CLIENT_ADDRESS_SUCCESS = "POST_CLIENT_ADDRESS_SUCCESS";
export const POST_CLIENT_ADDRESS_FAILURE = "POST_CLIENT_ADDRESS_FAILURE";

//POST API PHONE
export const POST_CLIENT_PHONE_SUCCESS = "POST_CLIENT_PHONE_SUCCESS";
export const POST_CLIENT_PHONE_FAILURE = "POST_CLIENT_PHONE_FAILURE";

//POST API PASSPORT
export const POST_CLIENT_PASSPORT_SUCCESS = "POST_CLIENT_PASSPORT_SUCCESS";
export const POST_CLIENT_PASSPORT_FAILURE = "POST_CLIENT_PASSPORT_FAILURE";

//POST API MEDICAL
export const POST_CLIENT_MEDICAL_SUCCESS = "POST_CLIENT_MEDICAL_SUCCESS";
export const POST_CLIENT_MEDICAL_FAILURE = "POST_CLIENT_MEDICAL_FAILURE";

//UPDATE CLIENT MEMBER
export const PUT_CLIENT_MEMBER_SUCCESS = "PUT_CLIENT_MEMBER_SUCCESS";
export const PUT_CLIENT_MEMBER_FAILURE = "PUT_CLIENT_MEMBER_FAILURE";

//GET EMPLOYRE INFORMATION
export const GET_EMPLOYRE_INFORMATION_SUCCESS =
  "GET_EMPLOYRE_INFORMATION_SUCCESS";
export const GET_EMPLOYRE_INFORMATION_FAILURE =
  "GET_EMPLOYRE_INFORMATION_FAILURE";

//POST EMPLOYRE INFORMATION
export const POST_EMPLOYRE_INFORMATION_SUCCESS =
  "POST_EMPLOYRE_INFORMATION_SUCCESS";
export const POST_EMPLOYRE_INFORMATION_FAILURE =
  "POST_EMPLOYRE_INFORMATION_FAILURE";

//PUT EMPLOYRE INFORMATION
export const PUT_EMPLOYRE_INFORMATION_SUCCESS =
  "PUT_EMPLOYRE_INFORMATION_SUCCESS";
export const PUT_EMPLOYRE_INFORMATION_FAILURE =
  "PUT_EMPLOYRE_INFORMATION_FAILURE";

//POST JOB HISTORY
export const POST_JOB_HISTORY_SUCCESS = "POST_JOB_HISTORY_SUCCESS";
export const POST_JOB_HISTORY_FAILURE = "POST_JOB_HISTORY_FAILURE";

//POST QUALIFICATION
export const POST_QUALIFICATION_SUCCESS = "POST_QUALIFICATION_SUCCESS";
export const POST_QUALIFICATION_FAILURE = "POST_QUALIFICATION_FAILURE";

//GET VISA STATUS
export const GET_VISA_STATUS_SUCCESS = "GET_VISA_STATUS_SUCCESS";
export const GET_VISA_STATUS_FAILURE = "GET_VISA_STATUS_FAILURE";

//GET ALL VISA STATUS
export const GET_ALL_VISA_STATUS_SUCCESS = "GET_ALL_VISA_STATUS_SUCCESS";
export const GET_ALL_VISA_STATUS_FAILURE = "GET_ALL_VISA_STATUS_FAILURE";

//GET ALL JOB HISTORY
export const GET_JOB_HISTORY_SUCCESS = "GET_JOB_HISTORY_SUCCESS";
export const GET_JOB_HISTORY_FAILURE = "GET_JOB_HISTORY_FAILURE";

//PUT JOB HISTORY
export const PUT_JOB_HISTORY_SUCCESS = "PUT_JOB_HISTORY_SUCCESS";
export const PUT_JOB_HISTORY_FAILURE = "PUT_JOB_HISTORY_FAILURE";

//GET EDUCATION HISTORY
export const GET_EDUCATION_HISTORY_SUCCESS = "GET_JOB_HISTORY_SUCCESS";
export const GET_EDUCATION_HISTORY_FAILURE = "GET_JOB_HISTORY_FAILURE";

//GET QUALIFICATION
export const GET_QUALIFICATION_SUCCESS = "GET_QUALIFICATION_SUCCESS";
export const GET_QUALIFICATION_FAILURE = "GET_QUALIFICATION_FAILURE";

//PUT QUALIFICATION
export const PUT_QUALIFICATION_SUCCESS = "PUT_QUALIFICATION_SUCCESS";
export const PUT_QUALIFICATION_FAILURE = "PUT_QUALIFICATION_FAILURE";

//GET COUNTRIES
export const GET_COUNTRIES_SUCCESS = "GET_COUNTRIES_SUCCESS";
export const GET_COUNTRIES_FAILURE = "GET_COUNTRIES_FAILURE";

//GET PARTNER JOB
export const GET_PARTNER_JOB_SUCCESS = "GET_PARTNER_JOB_SUCCESS";
export const GET_PARTNER_JOB_FAILURE = "GET_PARTNER_JOB_FAILURE";

//GET PARTNER QUALIFICATION
export const GET_PARTNER_QUALIFICATION_SUCCESS =
  "GET_PARTNER_QUALIFICATION_SUCCESS";
export const GET_PARTNER_QUALIFICATION_FAILURE =
  "GET_PARTNER_QUALIFICATION_FAILURE";
